preset: recommended

risky: false

linting: true

enabled:
  - logical_not_operators_with_successor_space
  - no_blank_lines_before_namespace

disabled:
  - blank_line_after_opening_tag
  - single_blank_line_before_namespace

finder:
  name:
    - "*.php"
  path:
    - ./app
    - ./resources/lang